# Generated by Django 4.0.4 on 2022-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=250)),
                ('im', models.ImageField(upload_to='pics')),
                ('dis', models.TextField()),
            ],
        ),
    ]
